# black-formatter.yml
name: Black Formatter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  black-formatting:

    runs-on: ubuntu-latest

    steps:
    # Check out most recent branch
    - name: Check out Branch
      uses: actions/checkout@v3

    # Setup python environment
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # Install python packages using a requirements file
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip cython wheel
        pip install -r requirements.txt

    # Format files with Black
    - name: Format with Black
      run: black .
